# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
windowrule = suppress_event maximize, match:class .*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0

# App-specific tweaks
source = ~/.local/share/omarchy/default/hypr/apps.conf

workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-2
workspace = 5, monitor:HDMI-A-1
workspace = 6, monitor:HDMI-A-1
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

windowrule = workspace 5, match:class ^(discord|Slack)$

# --- Development & Tools (WS 3, 5, 8, 9) ---
windowrule = workspace 3, match:class ^(TablePlus)$
windowrule = workspace 4, match:class ^(obsidian)$
windowrule = workspace 7, match:class ^(Postman)$

# --- Terminal & Browsers (WS 6, 7) ---
windowrule = workspace 1, match:class ^(.*alacritty)$
windowrule = workspace 1, match:class ^com\.mitchellh\.ghostty$
windowrule = workspace 2, match:class ^(brave-browser)$
windowrule = workspace 6, match:class ^(brave-chatgpt.com__-Default)$

# --- Media (WS 10) ---
windowrule = workspace 10, match:class ^(spotify)$
